name: Deploy Mbozor
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Deploy to Droplet
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.DROPLET_IP }}
        username: ${{ secrets.DROPLET_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd ~/Mbozor
          git pull
          source venv/bin/activate
          pip install -r requirements.txt
          sudo systemctl restart mbozor

